### PR TITLE
Update reference-entity-ids.tsv

### PR DESCRIPTION
**Pull request by emquardokus**
updated this file as per Kevin Hanshaw request on 12-14-2021 Added 77 new for ccf-release v1.1 to bottom of the previous v1.0 redirects.  
"Kevin Hanshaw:spiral_calendar_pad:  1:29 PM
You will want to use v1.0 and just add the information to the bottom of the other ones. I know proper Github etiquette is create new versions but the redirect service is already pointed at that version."

### CODE REVIEW

**Comment by emquardokus** [comment]
Kevin Hanshaw:spiral_calendar_pad:  1:29 PM
You will want to use v1.0 and just add the information to the bottom of the other ones. I know proper Github etiquette is create new versions but the redirect service is already pointed at that version.

**Comment by bherr2** [comment]
Any reason why this isn't commited to the v1.1 branch?

**Comment by emquardokus** [comment]
> Any reason why this isn't commited to the v1.1 branch?

This is what Kevin said because I asked the same thing: "Kevin Hanshaw:spiral_calendar_pad: 1:29 PM
You will want to use v1.0 and just add the information to the bottom of the other ones. I know proper Github etiquette is create new versions but the redirect service is already pointed at that version."

**Comment by bherr2** [comment]
Merging into the v1.1 branch until we make the v1.1 release. @khanshawPSC we'll be making the release soon, but didn't want to push to main until everything was done/verified.

**Comment by khanshawPSC** [comment]
@bherr2 the .tsv file needs to be at https://github.com/hubmapconsortium/ccf-releases/blob/main/v1.0/reference-entity-ids.tsv for it to work properly with the redirect service.

**Comment by bherr2** [comment]
That's fine, It'll be there when we merge the 1.1 release.

**Pull request merged**
